### ISSUE TITLE
Failed to start Ethereum

### ISSUE THREAD

**Issue by Sunyangyang12** [ehousecy/htlc-samples#2]
Hi，I can't start ETH。Errors is as follows.

Looking forward to your reply! Thanks.

--------------------Start ETH Node--------------------
nohup: appending output to 'nohup.out'
audited 370 packages in 2.971s

44 packages are looking for funding
  run `npm fund` for details

found 933 vulnerabilities (1 low, 360 moderate, 572 high)
  run `npm audit fix` to fix them, or `npm audit` for details

> htlc@1.0.0 inittsc /root/htlc/htlc-samples/htlc-eth
> tsc --init

error TS5054: A 'tsconfig.json' file is already defined at: '/root/htlc/htlc-samples/htlc-eth/tsconfig.json'.
sleep 15s to allow Miner to mine some ETH...

> htlc-client@1.0.0 frontier /root/htlc/htlc-samples/htlc-client
> ts-node src/service/preSetting.ts

/root/htlc/htlc-samples/htlc-client/node_modules/ts-node/src/index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/utils/Ifabric.ts:20:13 - error TS2571: Object is of type 'unknown'.

20       data: error.stack,
               ~~~~~
src/utils/Ifabric.ts:21:12 - error TS2571: Object is of type 'unknown'.

21       err: error.message
              ~~~~~

    at createTSError (/root/htlc/htlc-samples/htlc-client/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/root/htlc/htlc-samples/htlc-client/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/root/htlc/htlc-samples/htlc-client/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/root/htlc/htlc-samples/htlc-client/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/root/htlc/htlc-samples/htlc-client/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Object.require.extensions.<computed> [as .ts] (/root/htlc/htlc-samples/htlc-client/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! htlc-client@1.0.0 frontier: `ts-node src/service/preSetting.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the htlc-client@1.0.0 frontier script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-21T08_56_47_255Z-debug.log

> htlc-client@1.0.0 test /root/htlc/htlc-samples/htlc-client
> ts-node src/service/testWF.ts

/root/htlc/htlc-samples/htlc-client/node_modules/ts-node/src/index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/utils/Ifabric.ts:20:13 - error TS2571: Object is of type 'unknown'.

20       data: error.stack,
               ~~~~~
src/utils/Ifabric.ts:21:12 - error TS2571: Object is of type 'unknown'.

21       err: error.message
              ~~~~~

    at createTSError (/root/htlc/htlc-samples/htlc-client/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/root/htlc/htlc-samples/htlc-client/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/root/htlc/htlc-samples/htlc-client/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/root/htlc/htlc-samples/htlc-client/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/root/htlc/htlc-samples/htlc-client/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Object.require.extensions.<computed> [as .ts] (/root/htlc/htlc-samples/htlc-client/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/root/htlc/htlc-samples/htlc-client/src/service/testWF.ts:20:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Module.m._compile (/root/htlc/htlc-samples/htlc-client/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Object.require.extensions.<computed> [as .ts] (/root/htlc/htlc-samples/htlc-client/node_modules/ts-node/src/index.ts:1059:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! htlc-client@1.0.0 test: `ts-node src/service/testWF.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the htlc-client@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-21T08_56_51_536Z-debug.log

**Comment by telemember-sudo** [comment]
Have you solved your problem? I have encountered the same problem.If your problem is solved, I hope you can help me.Thanks !!

**Comment by Excuep** [comment]
--------------------Create Alice Account on Fabric--------------------
INPUT:
Alice's Account:  alice
Alice's PassWord:  alicepasswd 

OUTPUT:
RequestError: Error: connect ECONNREFUSED 127.0.0.1:9191
    at new RequestError (/Users/wushaoyang/workspace/src/github.com/hyperledger/htlc-samples/htlc-client/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/wushaoyang/workspace/src/github.com/hyperledger/htlc-samples/htlc-client/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/wushaoyang/workspace/src/github.com/hyperledger/htlc-samples/htlc-client/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/wushaoyang/workspace/src/github.com/hyperledger/htlc-samples/htlc-client/node_modules/request/request.js:185:22)
    at Request.emit (node:events:511:28)
    at Request.emit (node:domain:489:12)
    at Request.onRequestError (/Users/wushaoyang/workspace/src/github.com/hyperledger/htlc-samples/htlc-client/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:511:28)
    at ClientRequest.emit (node:domain:489:12)
    at Socket.socketErrorListener (node:_http_client:495:9)
    at Socket.emit (node:events:511:28)
    at Socket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)

想咨询一下怎么解决 小白卡壳好多天了
